### ISSUE TITLE
Enhancement : Tools to test that could be really broken

### ISSUE THREAD

**Issue by CinquinAndy** [CinquinAndy/formenu-front#62]
- [x] : [updrafts.app / features](https://updrafts.app/#)
- [ ] : [Transform every element on any website to Tailwind CSS with Windy](https://usewindy.com/#pricing)
- [ ] : [Windframe - Advanced Tailwind CSS page builder | Tailwind builder | Tailwind Editor | Visual Builder](https://www.devwares.com/windframe/pricing)
- [x] : [tailwind-classes-sorter](https://github.com/Acidic9/tailwind-classes-sorter) - NPM library which provides a utility to sort Tailwind CSS classes.
- [x] : [prettier-plugin-tailwind](https://github.com/Acidic9/prettier-plugin-tailwind) - Prettier plugin that sorts class lists.
- [x] : [Tailwind CSS Page Creator - Tails](https://devdojo.com/tails)

**Comment by CinquinAndy** [comment]
Je me suis peut être un peu emballé, enfaite c'est pas encore assez mature pour que ça soit vraiment une dinguerie à utiliser 
( fiiiiin, c'est sympa, mais c'est quand même vachement mieux de connaitre tailwindcss sur le bout des doigts ) 
-> donner tails à un débutant qui souhaite pas apprendre à coder peut être une bonne idée

**Comment by LightInn** [comment]
C'est que des outils payants de toute facon ?

**Comment by CinquinAndy** [comment]
yes, quasi tous, tous des versions gratuites, mais rien de très transcendant en vrai
